name: fe build and test
on:
  push:
  pull_request:
    branches: [main, develop]
    paths:
      - 'MinTurFrontend/**'

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        working-directory: 'MinTurFrontend/'
        run: npm i --legacy-peer-deps

      - name: Build
        working-directory: 'MinTurFrontend/'
        run: npm run build

      - name: Test
        working-directory: 'MinTurFrontend/'
        run: npm run test -- --prod
